language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t gaganpsgithub/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gaganpsgithub/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-T1"
  env: "Dockert1-env"
  bucket_name: "elasticbeanstalk-us-west-2-870065784475"
  bucket_path: "docker-T1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY